version: 2
jobs:
  test:
    docker:
      - image: docker:18.02.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t mps .
      - run:
          name: Test Code
          command: docker run mps

workflows:
    version: 2
    build:
        jobs:
            - test
